name: Push-playground

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Report summary
        uses: actions/github-script@v6
        with:
          script: |
            const script = require('./.github/workflows/do-annotations.js');
            script({github, context, core})
