on:
  push:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:

    - name: Check if update branch already exists
      id: check-existing-branch
      run: |
        set +o errexit
        git ls-remote --exit-code --heads "https://github.com/acoulton/actions-playground.git" "do-update"
        if [ $? -eq 0 ]; then
          echo "exists=true" >> $GITHUB_OUTPUT
          echo "checkout_branch=do-update" >> $GITHUB_OUTPUT
        else
          echo "exists=false" >> $GITHUB_OUTPUT
          echo "checkout_branch=master" >> $GITHUB_OUTPUT
        fi

    - uses: actions/checkout@v4
      with:
        ref: ${{ steps.check-existing-branch.outputs.checkout_branch }}

    - name: Create update branch if required
      if: steps.check-existing-branch.outputs.exists == 'false'
      run: git checkout -b do-update
