on:
  push:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:

    - name: Check if update branch already exists
      id: check-existing-branch
      run: |
        set +o errexit
        git ls-remote --exit-code --heads "https://github.com/acoulton/actions-playground.git" "do-update"
        if [ $? -eq 0 ]; then
          echo "exists=true" >> $GITHUB_OUTPUT
          echo "checkout_branch=do-update" >> $GITHUB_OUTPUT
        else
          echo "exists=false" >> $GITHUB_OUTPUT
          echo "checkout_branch=main" >> $GITHUB_OUTPUT
        fi

    - uses: actions/checkout@v4
      with:
        ref: ${{ steps.check-existing-branch.outputs.checkout_branch }}

    - name: Create update branch if required
      if: steps.check-existing-branch.outputs.exists == 'false'
      run: git checkout -b do-update

    - name: Make a commit msg
      id: msg
      run: |
        {
          echo 'commit_msg<<ENDOFVAR'
          echo 'Do a commit'
          echo ''
          echo 'With multiple lines'
          echo 'ENDOFVAR'
        } >> $GITHUB_OUTPUT

    - name: No changes this time but branch exists
      id: changes
      run: |
        date=`date`
        # echo $date >> test.txt
        echo "date=$date" >> $GITHUB_OUTPUT

    - name: Autocommit (no changes)
      id: commit
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        branch: do-update
        commit_message: ${{ steps.msg.outputs.commit_msg }}
        commit_author: 'github-actions[bot] <github-actions[bot]@users.noreply.github.com>'

    - name: Open or update PR
      if: steps.commit.outputs.changes_detected == 'true'
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        if [ "${{steps.check-existing-branch.outputs.exists}}" == 'false' ]; then
          gh pr create \
            --title="Do an automated thing ${{steps.changes.outputs.date}}" \
            --body="Automated things"
        else
          gh pr edit --title="Do an automated thing ${{steps.changes.outputs.date}}"
        fi
