name: Push-playground

on:
  push:
    branches: "*"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
     id-token: write
          
    steps:
      
      - name: Checkout actions-oidc-debugger
        uses: actions/checkout@v4
        with:
          repository: github/actions-oidc-debugger
          ref: main
          path: ./.github/actions/actions-oidc-debugger

      - name: Debug OIDC Claims
        uses: ./.github/actions/actions-oidc-debugger
        with:
          audience: '${{ github.server_url }}/${{ github.repository_owner }}'
